// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robinlg/agentops-platform/internal/runtime (interfaces: PromptBuilder)
//
// Generated by this command:
//
//	mockgen -destination mock_prompt_builder.go -package runtime github.com/robinlg/agentops-platform/internal/runtime PromptBuilder
//

// Package runtime is a generated GoMock package.
package runtime

import (
	reflect "reflect"

	llm "github.com/robinlg/agentops-platform/internal/llm"
	model "github.com/robinlg/agentops-platform/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockPromptBuilder is a mock of PromptBuilder interface.
type MockPromptBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockPromptBuilderMockRecorder
	isgomock struct{}
}

// MockPromptBuilderMockRecorder is the mock recorder for MockPromptBuilder.
type MockPromptBuilderMockRecorder struct {
	mock *MockPromptBuilder
}

// NewMockPromptBuilder creates a new mock instance.
func NewMockPromptBuilder(ctrl *gomock.Controller) *MockPromptBuilder {
	mock := &MockPromptBuilder{ctrl: ctrl}
	mock.recorder = &MockPromptBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromptBuilder) EXPECT() *MockPromptBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockPromptBuilder) Build(agent *model.AgentM, messages []*model.MessageM) []llm.Message {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", agent, messages)
	ret0, _ := ret[0].([]llm.Message)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *MockPromptBuilderMockRecorder) Build(agent, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockPromptBuilder)(nil).Build), agent, messages)
}
