// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robinlg/agentops-platform/internal/apiserver/biz (interfaces: IBiz)
//
// Generated by this command:
//
//	mockgen -destination mock_biz.go -package biz github.com/robinlg/agentops-platform/internal/apiserver/biz IBiz
//

// Package biz is a generated GoMock package.
package biz

import (
	reflect "reflect"

	model_provider "github.com/robinlg/agentops-platform/internal/apiserver/biz/v1/model-provider"
	gomock "go.uber.org/mock/gomock"
)

// MockIBiz is a mock of IBiz interface.
type MockIBiz struct {
	ctrl     *gomock.Controller
	recorder *MockIBizMockRecorder
	isgomock struct{}
}

// MockIBizMockRecorder is the mock recorder for MockIBiz.
type MockIBizMockRecorder struct {
	mock *MockIBiz
}

// NewMockIBiz creates a new mock instance.
func NewMockIBiz(ctrl *gomock.Controller) *MockIBiz {
	mock := &MockIBiz{ctrl: ctrl}
	mock.recorder = &MockIBizMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBiz) EXPECT() *MockIBizMockRecorder {
	return m.recorder
}

// ModelProviderV1 mocks base method.
func (m *MockIBiz) ModelProviderV1() model_provider.ModelProviderBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelProviderV1")
	ret0, _ := ret[0].(model_provider.ModelProviderBiz)
	return ret0
}

// ModelProviderV1 indicates an expected call of ModelProviderV1.
func (mr *MockIBizMockRecorder) ModelProviderV1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelProviderV1", reflect.TypeOf((*MockIBiz)(nil).ModelProviderV1))
}
