// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentRunM = "agent_runs"

// AgentRunM mapped from table <agent_runs>
type AgentRunM struct {
	ID               int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AgentID          int64      `gorm:"column:agent_id;not null;comment:智能体ID" json:"agent_id"`                              // 智能体ID
	ConversationID   int64      `gorm:"column:conversation_id;not null;comment:会话ID" json:"conversation_id"`                 // 会话ID
	Status           string     `gorm:"column:status;not null;comment:运行状态（pending/running/success/failed）" json:"status"`   // 运行状态（pending/running/success/failed）
	Input            *string    `gorm:"column:input;comment:输入内容" json:"input"`                                              // 输入内容
	Output           *string    `gorm:"column:output;comment:输出内容" json:"output"`                                            // 输出内容
	Model            *string    `gorm:"column:model;comment:使用的模型" json:"model"`                                             // 使用的模型
	PromptTokens     *int32     `gorm:"column:prompt_tokens;comment:输入token数" json:"prompt_tokens"`                          // 输入token数
	CompletionTokens *int32     `gorm:"column:completion_tokens;comment:输出token数" json:"completion_tokens"`                  // 输出token数
	TotalTokens      *int32     `gorm:"column:total_tokens;comment:总token数" json:"total_tokens"`                             // 总token数
	LatencyMs        *int64     `gorm:"column:latency_ms;comment:耗时（毫秒）" json:"latency_ms"`                                  // 耗时（毫秒）
	ErrorMessage     *string    `gorm:"column:error_message;comment:错误信息" json:"error_message"`                              // 错误信息
	StartedAt        time.Time  `gorm:"column:started_at;not null;default:CURRENT_TIMESTAMP;comment:开始时间" json:"started_at"` // 开始时间
	FinishedAt       *time.Time `gorm:"column:finished_at;comment:结束时间" json:"finished_at"`                                  // 结束时间
}

// TableName AgentRunM's table name
func (*AgentRunM) TableName() string {
	return TableNameAgentRunM
}
