// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConversationM = "conversations"

// ConversationM mapped from table <conversations>
type ConversationM struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AgentID   int64     `gorm:"column:agent_id;not null;comment:智能体ID" json:"agent_id"`                              // 智能体ID
	Title     *string   `gorm:"column:title;comment:会话标题" json:"title"`                                              // 会话标题
	CreatedAt time.Time `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName ConversationM's table name
func (*ConversationM) TableName() string {
	return TableNameConversationM
}
