// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessageM = "messages"

// MessageM mapped from table <messages>
type MessageM struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ConversationID int64     `gorm:"column:conversation_id;not null;comment:会话ID" json:"conversation_id"`                 // 会话ID
	Role           string    `gorm:"column:role;not null;comment:角色（user/assistant/system/tool）" json:"role"`             // 角色（user/assistant/system/tool）
	Content        string    `gorm:"column:content;not null;comment:消息内容" json:"content"`                                 // 消息内容
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName MessageM's table name
func (*MessageM) TableName() string {
	return TableNameMessageM
}
