// AgentRun API 定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: v1/agent_run.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentRun 表示一次智能体运行记录资源
type AgentRun struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主键 ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 智能体ID
	AgentId int64 `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// 会话ID
	ConversationId int64 `protobuf:"varint,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// 运行状态（pending/running/success/failed）
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// 输入内容
	Input *string `protobuf:"bytes,5,opt,name=input,proto3,oneof" json:"input,omitempty"`
	// 输出内容
	Output *string `protobuf:"bytes,6,opt,name=output,proto3,oneof" json:"output,omitempty"`
	// 使用的模型
	Model *string `protobuf:"bytes,7,opt,name=model,proto3,oneof" json:"model,omitempty"`
	// 输入token数
	PromptTokens *int32 `protobuf:"varint,8,opt,name=prompt_tokens,json=promptTokens,proto3,oneof" json:"prompt_tokens,omitempty"`
	// 输出token数
	CompletionTokens *int32 `protobuf:"varint,9,opt,name=completion_tokens,json=completionTokens,proto3,oneof" json:"completion_tokens,omitempty"`
	// 总token数
	TotalTokens *int32 `protobuf:"varint,10,opt,name=total_tokens,json=totalTokens,proto3,oneof" json:"total_tokens,omitempty"`
	// 耗时（毫秒）
	LatencyMs *int64 `protobuf:"varint,11,opt,name=latency_ms,json=latencyMs,proto3,oneof" json:"latency_ms,omitempty"`
	// 错误信息
	ErrorMessage *string `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	// 开始时间
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// 结束时间
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRun) Reset() {
	*x = AgentRun{}
	mi := &file_v1_agent_run_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRun) ProtoMessage() {}

func (x *AgentRun) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_run_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRun.ProtoReflect.Descriptor instead.
func (*AgentRun) Descriptor() ([]byte, []int) {
	return file_v1_agent_run_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRun) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgentRun) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentRun) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *AgentRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentRun) GetInput() string {
	if x != nil && x.Input != nil {
		return *x.Input
	}
	return ""
}

func (x *AgentRun) GetOutput() string {
	if x != nil && x.Output != nil {
		return *x.Output
	}
	return ""
}

func (x *AgentRun) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *AgentRun) GetPromptTokens() int32 {
	if x != nil && x.PromptTokens != nil {
		return *x.PromptTokens
	}
	return 0
}

func (x *AgentRun) GetCompletionTokens() int32 {
	if x != nil && x.CompletionTokens != nil {
		return *x.CompletionTokens
	}
	return 0
}

func (x *AgentRun) GetTotalTokens() int32 {
	if x != nil && x.TotalTokens != nil {
		return *x.TotalTokens
	}
	return 0
}

func (x *AgentRun) GetLatencyMs() int64 {
	if x != nil && x.LatencyMs != nil {
		return *x.LatencyMs
	}
	return 0
}

func (x *AgentRun) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *AgentRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *AgentRun) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

// ListAgentRunRequest 表示查询智能体运行记录列表的请求
type ListAgentRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentRunRequest) Reset() {
	*x = ListAgentRunRequest{}
	mi := &file_v1_agent_run_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentRunRequest) ProtoMessage() {}

func (x *ListAgentRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_run_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentRunRequest.ProtoReflect.Descriptor instead.
func (*ListAgentRunRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_run_proto_rawDescGZIP(), []int{1}
}

func (x *ListAgentRunRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAgentRunRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListAgentRunResponse 表示查询智能体运行记录列表的响应
type ListAgentRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	AgentRuns     []*AgentRun            `protobuf:"bytes,2,rep,name=agent_runs,json=agentRuns,proto3" json:"agent_runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentRunResponse) Reset() {
	*x = ListAgentRunResponse{}
	mi := &file_v1_agent_run_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentRunResponse) ProtoMessage() {}

func (x *ListAgentRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_run_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentRunResponse.ProtoReflect.Descriptor instead.
func (*ListAgentRunResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_run_proto_rawDescGZIP(), []int{2}
}

func (x *ListAgentRunResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListAgentRunResponse) GetAgentRuns() []*AgentRun {
	if x != nil {
		return x.AgentRuns
	}
	return nil
}

// GetAgentRunRequest 表示查询单个智能体运行记录的请求
type GetAgentRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRunRequest) Reset() {
	*x = GetAgentRunRequest{}
	mi := &file_v1_agent_run_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRunRequest) ProtoMessage() {}

func (x *GetAgentRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_run_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRunRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRunRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_run_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentRunRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetAgentRunResponse 表示查询单个智能体运行记录的响应
type GetAgentRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentRun      *AgentRun              `protobuf:"bytes,1,opt,name=agent_run,json=agentRun,proto3" json:"agent_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRunResponse) Reset() {
	*x = GetAgentRunResponse{}
	mi := &file_v1_agent_run_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRunResponse) ProtoMessage() {}

func (x *GetAgentRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_run_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRunResponse.ProtoReflect.Descriptor instead.
func (*GetAgentRunResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_run_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentRunResponse) GetAgentRun() *AgentRun {
	if x != nil {
		return x.AgentRun
	}
	return nil
}

var File_v1_agent_run_proto protoreflect.FileDescriptor

const file_v1_agent_run_proto_rawDesc = "" +
	"\n" +
	"\x12v1/agent_run.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x05\n" +
	"\bAgentRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\x03R\aagentId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\x03R\x0econversationId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x19\n" +
	"\x05input\x18\x05 \x01(\tH\x00R\x05input\x88\x01\x01\x12\x1b\n" +
	"\x06output\x18\x06 \x01(\tH\x01R\x06output\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\a \x01(\tH\x02R\x05model\x88\x01\x01\x12(\n" +
	"\rprompt_tokens\x18\b \x01(\x05H\x03R\fpromptTokens\x88\x01\x01\x120\n" +
	"\x11completion_tokens\x18\t \x01(\x05H\x04R\x10completionTokens\x88\x01\x01\x12&\n" +
	"\ftotal_tokens\x18\n" +
	" \x01(\x05H\x05R\vtotalTokens\x88\x01\x01\x12\"\n" +
	"\n" +
	"latency_ms\x18\v \x01(\x03H\x06R\tlatencyMs\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\f \x01(\tH\aR\ferrorMessage\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAtB\b\n" +
	"\x06_inputB\t\n" +
	"\a_outputB\b\n" +
	"\x06_modelB\x10\n" +
	"\x0e_prompt_tokensB\x14\n" +
	"\x12_completion_tokensB\x0f\n" +
	"\r_total_tokensB\r\n" +
	"\v_latency_msB\x10\n" +
	"\x0e_error_message\"C\n" +
	"\x13ListAgentRunRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"d\n" +
	"\x14ListAgentRunResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12+\n" +
	"\n" +
	"agent_runs\x18\x02 \x03(\v2\f.v1.AgentRunR\tagentRuns\"$\n" +
	"\x12GetAgentRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\x13GetAgentRunResponse\x12)\n" +
	"\tagent_run\x18\x01 \x01(\v2\f.v1.AgentRunR\bagentRunB4Z2github.com/robinlg/agentops-platform/pkg/api/v1;v1b\x06proto3"

var (
	file_v1_agent_run_proto_rawDescOnce sync.Once
	file_v1_agent_run_proto_rawDescData []byte
)

func file_v1_agent_run_proto_rawDescGZIP() []byte {
	file_v1_agent_run_proto_rawDescOnce.Do(func() {
		file_v1_agent_run_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_agent_run_proto_rawDesc), len(file_v1_agent_run_proto_rawDesc)))
	})
	return file_v1_agent_run_proto_rawDescData
}

var file_v1_agent_run_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_agent_run_proto_goTypes = []any{
	(*AgentRun)(nil),              // 0: v1.AgentRun
	(*ListAgentRunRequest)(nil),   // 1: v1.ListAgentRunRequest
	(*ListAgentRunResponse)(nil),  // 2: v1.ListAgentRunResponse
	(*GetAgentRunRequest)(nil),    // 3: v1.GetAgentRunRequest
	(*GetAgentRunResponse)(nil),   // 4: v1.GetAgentRunResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_v1_agent_run_proto_depIdxs = []int32{
	5, // 0: v1.AgentRun.started_at:type_name -> google.protobuf.Timestamp
	5, // 1: v1.AgentRun.finished_at:type_name -> google.protobuf.Timestamp
	0, // 2: v1.ListAgentRunResponse.agent_runs:type_name -> v1.AgentRun
	0, // 3: v1.GetAgentRunResponse.agent_run:type_name -> v1.AgentRun
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_agent_run_proto_init() }
func file_v1_agent_run_proto_init() {
	if File_v1_agent_run_proto != nil {
		return
	}
	file_v1_agent_run_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_agent_run_proto_rawDesc), len(file_v1_agent_run_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_agent_run_proto_goTypes,
		DependencyIndexes: file_v1_agent_run_proto_depIdxs,
		MessageInfos:      file_v1_agent_run_proto_msgTypes,
	}.Build()
	File_v1_agent_run_proto = out.File
	file_v1_agent_run_proto_goTypes = nil
	file_v1_agent_run_proto_depIdxs = nil
}
