// Chat API 定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: v1/chat.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateChatRequest 表示创建对话的请求
// agent_id 从 URI 路径参数绑定：POST /v1/agents/{id}/chat
type CreateChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 智能体ID（从 URI 绑定）
	// @gotags: uri:"id"
	AgentId int64 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty" uri:"id"`
	// 会话ID（可选，不传则创建新会话）
	ConversationId *int64 `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"`
	// 用户输入的消息
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *CreateChatRequest) GetConversationId() int64 {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return 0
}

func (x *CreateChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Usage token 使用量统计
type Usage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 输入 token 数
	PromptTokens int32 `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	// 输出 token 数
	CompletionTokens int32 `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	// 总 token 数
	TotalTokens   int32 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// CreateChatResponse 表示创建对话的响应
type CreateChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话ID
	ConversationId int64 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// 消息ID
	MessageId int64 `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// 运行记录ID
	RunId int64 `protobuf:"varint,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// 助手回复内容
	Answer string `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	// token 使用量
	Usage *Usage `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	// 耗时（毫秒）
	LatencyMs     int64 `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatResponse) Reset() {
	*x = CreateChatResponse{}
	mi := &file_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatResponse) ProtoMessage() {}

func (x *CreateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatResponse.ProtoReflect.Descriptor instead.
func (*CreateChatResponse) Descriptor() ([]byte, []int) {
	return file_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *CreateChatResponse) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *CreateChatResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *CreateChatResponse) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *CreateChatResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *CreateChatResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *CreateChatResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_v1_chat_proto protoreflect.FileDescriptor

const file_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\rv1/chat.proto\x12\x02v1\"\x8a\x01\n" +
	"\x11CreateChatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12,\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03H\x00R\x0econversationId\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB\x12\n" +
	"\x10_conversation_id\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"\xcb\x01\n" +
	"\x12CreateChatResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\x03R\x05runId\x12\x16\n" +
	"\x06answer\x18\x04 \x01(\tR\x06answer\x12\x1f\n" +
	"\x05usage\x18\x05 \x01(\v2\t.v1.UsageR\x05usage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMsB4Z2github.com/robinlg/agentops-platform/pkg/api/v1;v1b\x06proto3"

var (
	file_v1_chat_proto_rawDescOnce sync.Once
	file_v1_chat_proto_rawDescData []byte
)

func file_v1_chat_proto_rawDescGZIP() []byte {
	file_v1_chat_proto_rawDescOnce.Do(func() {
		file_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_chat_proto_rawDesc), len(file_v1_chat_proto_rawDesc)))
	})
	return file_v1_chat_proto_rawDescData
}

var file_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_chat_proto_goTypes = []any{
	(*CreateChatRequest)(nil),  // 0: v1.CreateChatRequest
	(*Usage)(nil),              // 1: v1.Usage
	(*CreateChatResponse)(nil), // 2: v1.CreateChatResponse
}
var file_v1_chat_proto_depIdxs = []int32{
	1, // 0: v1.CreateChatResponse.usage:type_name -> v1.Usage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_chat_proto_init() }
func file_v1_chat_proto_init() {
	if File_v1_chat_proto != nil {
		return
	}
	file_v1_chat_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_chat_proto_rawDesc), len(file_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_chat_proto_goTypes,
		DependencyIndexes: file_v1_chat_proto_depIdxs,
		MessageInfos:      file_v1_chat_proto_msgTypes,
	}.Build()
	File_v1_chat_proto = out.File
	file_v1_chat_proto_goTypes = nil
	file_v1_chat_proto_depIdxs = nil
}
