// Conversation API 定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: v1/conversation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Conversation 表示一个会话资源
type Conversation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主键 ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 智能体ID
	AgentId int64 `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// 会话标题
	Title *string `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// 创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_v1_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_v1_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_v1_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Conversation) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *Conversation) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Conversation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Conversation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Message 表示一条会话消息资源
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主键 ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 会话ID
	ConversationId int64 `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// 角色（user/assistant/system/tool）
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// 消息内容
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// 创建时间
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_v1_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_v1_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_v1_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListConversationRequest 表示查询会话列表的请求
type ListConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationRequest) Reset() {
	*x = ListConversationRequest{}
	mi := &file_v1_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationRequest) ProtoMessage() {}

func (x *ListConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationRequest.ProtoReflect.Descriptor instead.
func (*ListConversationRequest) Descriptor() ([]byte, []int) {
	return file_v1_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *ListConversationRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListConversationRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListConversationResponse 表示查询会话列表的响应
type ListConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Conversations []*Conversation        `protobuf:"bytes,2,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationResponse) Reset() {
	*x = ListConversationResponse{}
	mi := &file_v1_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationResponse) ProtoMessage() {}

func (x *ListConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationResponse.ProtoReflect.Descriptor instead.
func (*ListConversationResponse) Descriptor() ([]byte, []int) {
	return file_v1_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *ListConversationResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListConversationResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

// ListMessageRequest 表示查询会话消息列表的请求
type ListMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"id"
	ConversationId int64 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty" uri:"id"`
	Offset         int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit          int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMessageRequest) Reset() {
	*x = ListMessageRequest{}
	mi := &file_v1_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageRequest) ProtoMessage() {}

func (x *ListMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageRequest.ProtoReflect.Descriptor instead.
func (*ListMessageRequest) Descriptor() ([]byte, []int) {
	return file_v1_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *ListMessageRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ListMessageRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMessageRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListMessageResponse 表示查询会话消息列表的响应
type ListMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageResponse) Reset() {
	*x = ListMessageResponse{}
	mi := &file_v1_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageResponse) ProtoMessage() {}

func (x *ListMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageResponse.ProtoReflect.Descriptor instead.
func (*ListMessageResponse) Descriptor() ([]byte, []int) {
	return file_v1_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *ListMessageResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMessageResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// DeleteConversationRequest 表示删除会话的请求
type DeleteConversationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationRequest) Reset() {
	*x = DeleteConversationRequest{}
	mi := &file_v1_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationRequest) ProtoMessage() {}

func (x *DeleteConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return file_v1_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteConversationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteConversationResponse 表示删除会话的响应
type DeleteConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationResponse) Reset() {
	*x = DeleteConversationResponse{}
	mi := &file_v1_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationResponse) ProtoMessage() {}

func (x *DeleteConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationResponse.ProtoReflect.Descriptor instead.
func (*DeleteConversationResponse) Descriptor() ([]byte, []int) {
	return file_v1_conversation_proto_rawDescGZIP(), []int{7}
}

var File_v1_conversation_proto protoreflect.FileDescriptor

const file_v1_conversation_proto_rawDesc = "" +
	"\n" +
	"\x15v1/conversation.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\x03R\aagentId\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\b\n" +
	"\x06_title\"\xab\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"G\n" +
	"\x17ListConversationRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"s\n" +
	"\x18ListConversationResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x126\n" +
	"\rconversations\x18\x02 \x03(\v2\x10.v1.ConversationR\rconversations\"k\n" +
	"\x12ListMessageRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"_\n" +
	"\x13ListMessageResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12'\n" +
	"\bmessages\x18\x02 \x03(\v2\v.v1.MessageR\bmessages\"+\n" +
	"\x19DeleteConversationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1c\n" +
	"\x1aDeleteConversationResponseB4Z2github.com/robinlg/agentops-platform/pkg/api/v1;v1b\x06proto3"

var (
	file_v1_conversation_proto_rawDescOnce sync.Once
	file_v1_conversation_proto_rawDescData []byte
)

func file_v1_conversation_proto_rawDescGZIP() []byte {
	file_v1_conversation_proto_rawDescOnce.Do(func() {
		file_v1_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_conversation_proto_rawDesc), len(file_v1_conversation_proto_rawDesc)))
	})
	return file_v1_conversation_proto_rawDescData
}

var file_v1_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_conversation_proto_goTypes = []any{
	(*Conversation)(nil),               // 0: v1.Conversation
	(*Message)(nil),                    // 1: v1.Message
	(*ListConversationRequest)(nil),    // 2: v1.ListConversationRequest
	(*ListConversationResponse)(nil),   // 3: v1.ListConversationResponse
	(*ListMessageRequest)(nil),         // 4: v1.ListMessageRequest
	(*ListMessageResponse)(nil),        // 5: v1.ListMessageResponse
	(*DeleteConversationRequest)(nil),  // 6: v1.DeleteConversationRequest
	(*DeleteConversationResponse)(nil), // 7: v1.DeleteConversationResponse
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
}
var file_v1_conversation_proto_depIdxs = []int32{
	8, // 0: v1.Conversation.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: v1.Conversation.updated_at:type_name -> google.protobuf.Timestamp
	8, // 2: v1.Message.created_at:type_name -> google.protobuf.Timestamp
	0, // 3: v1.ListConversationResponse.conversations:type_name -> v1.Conversation
	1, // 4: v1.ListMessageResponse.messages:type_name -> v1.Message
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_conversation_proto_init() }
func file_v1_conversation_proto_init() {
	if File_v1_conversation_proto != nil {
		return
	}
	file_v1_conversation_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_conversation_proto_rawDesc), len(file_v1_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_conversation_proto_goTypes,
		DependencyIndexes: file_v1_conversation_proto_depIdxs,
		MessageInfos:      file_v1_conversation_proto_msgTypes,
	}.Build()
	File_v1_conversation_proto = out.File
	file_v1_conversation_proto_goTypes = nil
	file_v1_conversation_proto_depIdxs = nil
}
