// ModelProvider API 定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: v1/model_provider.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ModelProvider 表示一个模型提供商资源
type ModelProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主键 ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 模型提供商名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 模型提供商类型（如 openai、anthropic、azure 等）
	ProviderType string `protobuf:"bytes,3,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	// 模型提供商访问 URL
	BaseUrl string `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// 模型提供商 API KEY（对外返回时建议由业务层脱敏）
	ApiKey string `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// 默认使用的模型名称
	DefaultModel string `protobuf:"bytes,6,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	// 创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelProvider) Reset() {
	*x = ModelProvider{}
	mi := &file_v1_model_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProvider) ProtoMessage() {}

func (x *ModelProvider) ProtoReflect() protoreflect.Message {
	mi := &file_v1_model_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProvider.ProtoReflect.Descriptor instead.
func (*ModelProvider) Descriptor() ([]byte, []int) {
	return file_v1_model_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ModelProvider) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelProvider) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *ModelProvider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ModelProvider) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ModelProvider) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

func (x *ModelProvider) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ModelProvider) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateModelProviderRequest 表示创建模型提供商的请求
type CreateModelProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 模型提供商名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 模型提供商类型
	ProviderType string `protobuf:"bytes,2,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	// 模型提供商访问 URL
	BaseUrl string `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// 模型提供商 API KEY
	ApiKey string `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// 默认使用的模型名称
	DefaultModel  string `protobuf:"bytes,5,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelProviderRequest) Reset() {
	*x = CreateModelProviderRequest{}
	mi := &file_v1_model_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelProviderRequest) ProtoMessage() {}

func (x *CreateModelProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_model_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateModelProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_model_provider_proto_rawDescGZIP(), []int{1}
}

func (x *CreateModelProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelProviderRequest) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *CreateModelProviderRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CreateModelProviderRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateModelProviderRequest) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

// CreateModelProviderResponse 表示创建模型提供商的响应
type CreateModelProviderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 新创建模型提供商的 ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelProviderResponse) Reset() {
	*x = CreateModelProviderResponse{}
	mi := &file_v1_model_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelProviderResponse) ProtoMessage() {}

func (x *CreateModelProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_model_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelProviderResponse.ProtoReflect.Descriptor instead.
func (*CreateModelProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_model_provider_proto_rawDescGZIP(), []int{2}
}

func (x *CreateModelProviderResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ListModelProviderRequest 表示查询模型提供商列表的请求
type ListModelProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 偏移量，用于分页
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// 每页数量限制
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelProviderRequest) Reset() {
	*x = ListModelProviderRequest{}
	mi := &file_v1_model_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelProviderRequest) ProtoMessage() {}

func (x *ListModelProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_model_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelProviderRequest.ProtoReflect.Descriptor instead.
func (*ListModelProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_model_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ListModelProviderRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListModelProviderRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListModelProviderResponse 表示查询模型提供商列表的响应
type ListModelProviderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 满足条件的总条数
	TotalCount int64 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// 当前页的模型提供商列表
	ModelProviders []*ModelProvider `protobuf:"bytes,2,rep,name=model_providers,json=modelProviders,proto3" json:"model_providers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListModelProviderResponse) Reset() {
	*x = ListModelProviderResponse{}
	mi := &file_v1_model_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelProviderResponse) ProtoMessage() {}

func (x *ListModelProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_model_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelProviderResponse.ProtoReflect.Descriptor instead.
func (*ListModelProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_model_provider_proto_rawDescGZIP(), []int{4}
}

func (x *ListModelProviderResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListModelProviderResponse) GetModelProviders() []*ModelProvider {
	if x != nil {
		return x.ModelProviders
	}
	return nil
}

// GetModelProviderRequest 表示查询单个模型提供商的请求
type GetModelProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 模型提供商 ID
	// @gotags: uri:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelProviderRequest) Reset() {
	*x = GetModelProviderRequest{}
	mi := &file_v1_model_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelProviderRequest) ProtoMessage() {}

func (x *GetModelProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_model_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelProviderRequest.ProtoReflect.Descriptor instead.
func (*GetModelProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_model_provider_proto_rawDescGZIP(), []int{5}
}

func (x *GetModelProviderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetModelProviderResponse 表示查询单个模型提供商的响应
type GetModelProviderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 模型提供商详情
	ModelProvider *ModelProvider `protobuf:"bytes,1,opt,name=model_provider,json=modelProvider,proto3" json:"model_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelProviderResponse) Reset() {
	*x = GetModelProviderResponse{}
	mi := &file_v1_model_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelProviderResponse) ProtoMessage() {}

func (x *GetModelProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_model_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelProviderResponse.ProtoReflect.Descriptor instead.
func (*GetModelProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_model_provider_proto_rawDescGZIP(), []int{6}
}

func (x *GetModelProviderResponse) GetModelProvider() *ModelProvider {
	if x != nil {
		return x.ModelProvider
	}
	return nil
}

// UpdateModelProviderRequest 表示更新模型提供商的请求
// 使用 optional 字段，未设置的字段将不参与更新（部分更新语义）
type UpdateModelProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 待更新的模型提供商 ID
	// @gotags: uri:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" uri:"id"`
	// 模型提供商名称
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// 模型提供商类型
	ProviderType *string `protobuf:"bytes,3,opt,name=provider_type,json=providerType,proto3,oneof" json:"provider_type,omitempty"`
	// 模型提供商访问 URL
	BaseUrl *string `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3,oneof" json:"base_url,omitempty"`
	// 模型提供商 API KEY
	ApiKey *string `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3,oneof" json:"api_key,omitempty"`
	// 默认使用的模型名称
	DefaultModel  *string `protobuf:"bytes,6,opt,name=default_model,json=defaultModel,proto3,oneof" json:"default_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelProviderRequest) Reset() {
	*x = UpdateModelProviderRequest{}
	mi := &file_v1_model_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelProviderRequest) ProtoMessage() {}

func (x *UpdateModelProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_model_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_model_provider_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateModelProviderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateModelProviderRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateModelProviderRequest) GetProviderType() string {
	if x != nil && x.ProviderType != nil {
		return *x.ProviderType
	}
	return ""
}

func (x *UpdateModelProviderRequest) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return ""
}

func (x *UpdateModelProviderRequest) GetApiKey() string {
	if x != nil && x.ApiKey != nil {
		return *x.ApiKey
	}
	return ""
}

func (x *UpdateModelProviderRequest) GetDefaultModel() string {
	if x != nil && x.DefaultModel != nil {
		return *x.DefaultModel
	}
	return ""
}

// UpdateModelProviderResponse 表示更新模型提供商的响应
type UpdateModelProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelProviderResponse) Reset() {
	*x = UpdateModelProviderResponse{}
	mi := &file_v1_model_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelProviderResponse) ProtoMessage() {}

func (x *UpdateModelProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_model_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelProviderResponse.ProtoReflect.Descriptor instead.
func (*UpdateModelProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_model_provider_proto_rawDescGZIP(), []int{8}
}

// DeleteModelProviderRequest 表示删除模型提供商的请求
type DeleteModelProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 待删除的模型提供商 ID
	// @gotags: uri:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelProviderRequest) Reset() {
	*x = DeleteModelProviderRequest{}
	mi := &file_v1_model_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelProviderRequest) ProtoMessage() {}

func (x *DeleteModelProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_model_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_model_provider_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteModelProviderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteModelProviderResponse 表示删除模型提供商的响应
type DeleteModelProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelProviderResponse) Reset() {
	*x = DeleteModelProviderResponse{}
	mi := &file_v1_model_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelProviderResponse) ProtoMessage() {}

func (x *DeleteModelProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_model_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelProviderResponse.ProtoReflect.Descriptor instead.
func (*DeleteModelProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_model_provider_proto_rawDescGZIP(), []int{10}
}

var File_v1_model_provider_proto protoreflect.FileDescriptor

const file_v1_model_provider_proto_rawDesc = "" +
	"\n" +
	"\x17v1/model_provider.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x02\n" +
	"\rModelProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rprovider_type\x18\x03 \x01(\tR\fproviderType\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\x12#\n" +
	"\rdefault_model\x18\x06 \x01(\tR\fdefaultModel\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xae\x01\n" +
	"\x1aCreateModelProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rprovider_type\x18\x02 \x01(\tR\fproviderType\x12\x19\n" +
	"\bbase_url\x18\x03 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12#\n" +
	"\rdefault_model\x18\x05 \x01(\tR\fdefaultModel\"-\n" +
	"\x1bCreateModelProviderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"H\n" +
	"\x18ListModelProviderRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"x\n" +
	"\x19ListModelProviderResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12:\n" +
	"\x0fmodel_providers\x18\x02 \x03(\v2\x11.v1.ModelProviderR\x0emodelProviders\")\n" +
	"\x17GetModelProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"T\n" +
	"\x18GetModelProviderResponse\x128\n" +
	"\x0emodel_provider\x18\x01 \x01(\v2\x11.v1.ModelProviderR\rmodelProvider\"\x9d\x02\n" +
	"\x1aUpdateModelProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12(\n" +
	"\rprovider_type\x18\x03 \x01(\tH\x01R\fproviderType\x88\x01\x01\x12\x1e\n" +
	"\bbase_url\x18\x04 \x01(\tH\x02R\abaseUrl\x88\x01\x01\x12\x1c\n" +
	"\aapi_key\x18\x05 \x01(\tH\x03R\x06apiKey\x88\x01\x01\x12(\n" +
	"\rdefault_model\x18\x06 \x01(\tH\x04R\fdefaultModel\x88\x01\x01B\a\n" +
	"\x05_nameB\x10\n" +
	"\x0e_provider_typeB\v\n" +
	"\t_base_urlB\n" +
	"\n" +
	"\b_api_keyB\x10\n" +
	"\x0e_default_model\"\x1d\n" +
	"\x1bUpdateModelProviderResponse\",\n" +
	"\x1aDeleteModelProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1d\n" +
	"\x1bDeleteModelProviderResponseB4Z2github.com/robinlg/agentops-platform/pkg/api/v1;v1b\x06proto3"

var (
	file_v1_model_provider_proto_rawDescOnce sync.Once
	file_v1_model_provider_proto_rawDescData []byte
)

func file_v1_model_provider_proto_rawDescGZIP() []byte {
	file_v1_model_provider_proto_rawDescOnce.Do(func() {
		file_v1_model_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_model_provider_proto_rawDesc), len(file_v1_model_provider_proto_rawDesc)))
	})
	return file_v1_model_provider_proto_rawDescData
}

var file_v1_model_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_model_provider_proto_goTypes = []any{
	(*ModelProvider)(nil),               // 0: v1.ModelProvider
	(*CreateModelProviderRequest)(nil),  // 1: v1.CreateModelProviderRequest
	(*CreateModelProviderResponse)(nil), // 2: v1.CreateModelProviderResponse
	(*ListModelProviderRequest)(nil),    // 3: v1.ListModelProviderRequest
	(*ListModelProviderResponse)(nil),   // 4: v1.ListModelProviderResponse
	(*GetModelProviderRequest)(nil),     // 5: v1.GetModelProviderRequest
	(*GetModelProviderResponse)(nil),    // 6: v1.GetModelProviderResponse
	(*UpdateModelProviderRequest)(nil),  // 7: v1.UpdateModelProviderRequest
	(*UpdateModelProviderResponse)(nil), // 8: v1.UpdateModelProviderResponse
	(*DeleteModelProviderRequest)(nil),  // 9: v1.DeleteModelProviderRequest
	(*DeleteModelProviderResponse)(nil), // 10: v1.DeleteModelProviderResponse
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
}
var file_v1_model_provider_proto_depIdxs = []int32{
	11, // 0: v1.ModelProvider.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: v1.ModelProvider.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: v1.ListModelProviderResponse.model_providers:type_name -> v1.ModelProvider
	0,  // 3: v1.GetModelProviderResponse.model_provider:type_name -> v1.ModelProvider
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_v1_model_provider_proto_init() }
func file_v1_model_provider_proto_init() {
	if File_v1_model_provider_proto != nil {
		return
	}
	file_v1_model_provider_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_model_provider_proto_rawDesc), len(file_v1_model_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_model_provider_proto_goTypes,
		DependencyIndexes: file_v1_model_provider_proto_depIdxs,
		MessageInfos:      file_v1_model_provider_proto_msgTypes,
	}.Build()
	File_v1_model_provider_proto = out.File
	file_v1_model_provider_proto_goTypes = nil
	file_v1_model_provider_proto_depIdxs = nil
}
