// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robinlg/agentops-platform/internal/store (interfaces: MessageStore)
//
// Generated by this command:
//
//	mockgen -destination mock_message.go -package store github.com/robinlg/agentops-platform/internal/store MessageStore
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	model "github.com/robinlg/agentops-platform/internal/model"
	where "github.com/robinlg/onexlib/pkg/store/where"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageStore is a mock of MessageStore interface.
type MockMessageStore struct {
	ctrl     *gomock.Controller
	recorder *MockMessageStoreMockRecorder
	isgomock struct{}
}

// MockMessageStoreMockRecorder is the mock recorder for MockMessageStore.
type MockMessageStoreMockRecorder struct {
	mock *MockMessageStore
}

// NewMockMessageStore creates a new mock instance.
func NewMockMessageStore(ctrl *gomock.Controller) *MockMessageStore {
	mock := &MockMessageStore{ctrl: ctrl}
	mock.recorder = &MockMessageStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageStore) EXPECT() *MockMessageStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMessageStore) Create(ctx context.Context, obj *model.MessageM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMessageStoreMockRecorder) Create(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageStore)(nil).Create), ctx, obj)
}

// Delete mocks base method.
func (m *MockMessageStore) Delete(ctx context.Context, opts *where.Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMessageStoreMockRecorder) Delete(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMessageStore)(nil).Delete), ctx, opts)
}

// Get mocks base method.
func (m *MockMessageStore) Get(ctx context.Context, opts *where.Options) (*model.MessageM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, opts)
	ret0, _ := ret[0].(*model.MessageM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMessageStoreMockRecorder) Get(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMessageStore)(nil).Get), ctx, opts)
}

// List mocks base method.
func (m *MockMessageStore) List(ctx context.Context, opts *where.Options) (int64, []*model.MessageM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]*model.MessageM)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockMessageStoreMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMessageStore)(nil).List), ctx, opts)
}

// Update mocks base method.
func (m *MockMessageStore) Update(ctx context.Context, obj *model.MessageM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMessageStoreMockRecorder) Update(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMessageStore)(nil).Update), ctx, obj)
}
