// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robinlg/agentops-platform/internal/store (interfaces: ConversationStore)
//
// Generated by this command:
//
//	mockgen -destination mock_conversation.go -package store github.com/robinlg/agentops-platform/internal/store ConversationStore
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	model "github.com/robinlg/agentops-platform/internal/model"
	where "github.com/robinlg/onexlib/pkg/store/where"
	gomock "go.uber.org/mock/gomock"
)

// MockConversationStore is a mock of ConversationStore interface.
type MockConversationStore struct {
	ctrl     *gomock.Controller
	recorder *MockConversationStoreMockRecorder
	isgomock struct{}
}

// MockConversationStoreMockRecorder is the mock recorder for MockConversationStore.
type MockConversationStoreMockRecorder struct {
	mock *MockConversationStore
}

// NewMockConversationStore creates a new mock instance.
func NewMockConversationStore(ctrl *gomock.Controller) *MockConversationStore {
	mock := &MockConversationStore{ctrl: ctrl}
	mock.recorder = &MockConversationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationStore) EXPECT() *MockConversationStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConversationStore) Create(ctx context.Context, obj *model.ConversationM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockConversationStoreMockRecorder) Create(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConversationStore)(nil).Create), ctx, obj)
}

// Delete mocks base method.
func (m *MockConversationStore) Delete(ctx context.Context, opts *where.Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConversationStoreMockRecorder) Delete(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConversationStore)(nil).Delete), ctx, opts)
}

// Get mocks base method.
func (m *MockConversationStore) Get(ctx context.Context, opts *where.Options) (*model.ConversationM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, opts)
	ret0, _ := ret[0].(*model.ConversationM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConversationStoreMockRecorder) Get(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConversationStore)(nil).Get), ctx, opts)
}

// List mocks base method.
func (m *MockConversationStore) List(ctx context.Context, opts *where.Options) (int64, []*model.ConversationM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]*model.ConversationM)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockConversationStoreMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConversationStore)(nil).List), ctx, opts)
}

// Update mocks base method.
func (m *MockConversationStore) Update(ctx context.Context, obj *model.ConversationM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockConversationStoreMockRecorder) Update(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConversationStore)(nil).Update), ctx, obj)
}
