// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robinlg/agentops-platform/internal/store (interfaces: AgentStore)
//
// Generated by this command:
//
//	mockgen -destination mock_agent.go -package store github.com/robinlg/agentops-platform/internal/store AgentStore
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	model "github.com/robinlg/agentops-platform/internal/model"
	where "github.com/robinlg/onexlib/pkg/store/where"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentStore is a mock of AgentStore interface.
type MockAgentStore struct {
	ctrl     *gomock.Controller
	recorder *MockAgentStoreMockRecorder
	isgomock struct{}
}

// MockAgentStoreMockRecorder is the mock recorder for MockAgentStore.
type MockAgentStoreMockRecorder struct {
	mock *MockAgentStore
}

// NewMockAgentStore creates a new mock instance.
func NewMockAgentStore(ctrl *gomock.Controller) *MockAgentStore {
	mock := &MockAgentStore{ctrl: ctrl}
	mock.recorder = &MockAgentStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentStore) EXPECT() *MockAgentStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAgentStore) Create(ctx context.Context, obj *model.AgentM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAgentStoreMockRecorder) Create(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentStore)(nil).Create), ctx, obj)
}

// Delete mocks base method.
func (m *MockAgentStore) Delete(ctx context.Context, opts *where.Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentStoreMockRecorder) Delete(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentStore)(nil).Delete), ctx, opts)
}

// Get mocks base method.
func (m *MockAgentStore) Get(ctx context.Context, opts *where.Options) (*model.AgentM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, opts)
	ret0, _ := ret[0].(*model.AgentM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAgentStoreMockRecorder) Get(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentStore)(nil).Get), ctx, opts)
}

// List mocks base method.
func (m *MockAgentStore) List(ctx context.Context, opts *where.Options) (int64, []*model.AgentM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]*model.AgentM)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAgentStoreMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAgentStore)(nil).List), ctx, opts)
}

// Update mocks base method.
func (m *MockAgentStore) Update(ctx context.Context, obj *model.AgentM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAgentStoreMockRecorder) Update(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAgentStore)(nil).Update), ctx, obj)
}
