// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robinlg/agentops-platform/internal/store (interfaces: ModelProviderStore)
//
// Generated by this command:
//
//	mockgen -destination mock_model_provider.go -package store github.com/robinlg/agentops-platform/internal/store ModelProviderStore
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	model "github.com/robinlg/agentops-platform/internal/model"
	where "github.com/robinlg/onexlib/pkg/store/where"
	gomock "go.uber.org/mock/gomock"
)

// MockModelProviderStore is a mock of ModelProviderStore interface.
type MockModelProviderStore struct {
	ctrl     *gomock.Controller
	recorder *MockModelProviderStoreMockRecorder
	isgomock struct{}
}

// MockModelProviderStoreMockRecorder is the mock recorder for MockModelProviderStore.
type MockModelProviderStoreMockRecorder struct {
	mock *MockModelProviderStore
}

// NewMockModelProviderStore creates a new mock instance.
func NewMockModelProviderStore(ctrl *gomock.Controller) *MockModelProviderStore {
	mock := &MockModelProviderStore{ctrl: ctrl}
	mock.recorder = &MockModelProviderStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelProviderStore) EXPECT() *MockModelProviderStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockModelProviderStore) Create(ctx context.Context, obj *model.ModelProviderM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockModelProviderStoreMockRecorder) Create(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockModelProviderStore)(nil).Create), ctx, obj)
}

// Delete mocks base method.
func (m *MockModelProviderStore) Delete(ctx context.Context, opts *where.Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockModelProviderStoreMockRecorder) Delete(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockModelProviderStore)(nil).Delete), ctx, opts)
}

// Get mocks base method.
func (m *MockModelProviderStore) Get(ctx context.Context, opts *where.Options) (*model.ModelProviderM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, opts)
	ret0, _ := ret[0].(*model.ModelProviderM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockModelProviderStoreMockRecorder) Get(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockModelProviderStore)(nil).Get), ctx, opts)
}

// List mocks base method.
func (m *MockModelProviderStore) List(ctx context.Context, opts *where.Options) (int64, []*model.ModelProviderM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]*model.ModelProviderM)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockModelProviderStoreMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockModelProviderStore)(nil).List), ctx, opts)
}

// Update mocks base method.
func (m *MockModelProviderStore) Update(ctx context.Context, obj *model.ModelProviderM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockModelProviderStoreMockRecorder) Update(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockModelProviderStore)(nil).Update), ctx, obj)
}
