// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robinlg/agentops-platform/internal/store (interfaces: IStore)
//
// Generated by this command:
//
//	mockgen -destination mock_store.go -package store github.com/robinlg/agentops-platform/internal/store IStore
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	where "github.com/robinlg/onexlib/pkg/store/where"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockIStore is a mock of IStore interface.
type MockIStore struct {
	ctrl     *gomock.Controller
	recorder *MockIStoreMockRecorder
	isgomock struct{}
}

// MockIStoreMockRecorder is the mock recorder for MockIStore.
type MockIStoreMockRecorder struct {
	mock *MockIStore
}

// NewMockIStore creates a new mock instance.
func NewMockIStore(ctrl *gomock.Controller) *MockIStore {
	mock := &MockIStore{ctrl: ctrl}
	mock.recorder = &MockIStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStore) EXPECT() *MockIStoreMockRecorder {
	return m.recorder
}

// Agent mocks base method.
func (m *MockIStore) Agent() AgentStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Agent")
	ret0, _ := ret[0].(AgentStore)
	return ret0
}

// Agent indicates an expected call of Agent.
func (mr *MockIStoreMockRecorder) Agent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Agent", reflect.TypeOf((*MockIStore)(nil).Agent))
}

// AgentRun mocks base method.
func (m *MockIStore) AgentRun() AgentRunStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentRun")
	ret0, _ := ret[0].(AgentRunStore)
	return ret0
}

// AgentRun indicates an expected call of AgentRun.
func (mr *MockIStoreMockRecorder) AgentRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentRun", reflect.TypeOf((*MockIStore)(nil).AgentRun))
}

// Conversation mocks base method.
func (m *MockIStore) Conversation() ConversationStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Conversation")
	ret0, _ := ret[0].(ConversationStore)
	return ret0
}

// Conversation indicates an expected call of Conversation.
func (mr *MockIStoreMockRecorder) Conversation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Conversation", reflect.TypeOf((*MockIStore)(nil).Conversation))
}

// DB mocks base method.
func (m *MockIStore) DB(ctx context.Context, wheres ...where.Where) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range wheres {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DB", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockIStoreMockRecorder) DB(ctx any, wheres ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, wheres...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockIStore)(nil).DB), varargs...)
}

// Message mocks base method.
func (m *MockIStore) Message() MessageStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Message")
	ret0, _ := ret[0].(MessageStore)
	return ret0
}

// Message indicates an expected call of Message.
func (mr *MockIStoreMockRecorder) Message() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Message", reflect.TypeOf((*MockIStore)(nil).Message))
}

// ModelProvider mocks base method.
func (m *MockIStore) ModelProvider() ModelProviderStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelProvider")
	ret0, _ := ret[0].(ModelProviderStore)
	return ret0
}

// ModelProvider indicates an expected call of ModelProvider.
func (mr *MockIStoreMockRecorder) ModelProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelProvider", reflect.TypeOf((*MockIStore)(nil).ModelProvider))
}

// TX mocks base method.
func (m *MockIStore) TX(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TX", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// TX indicates an expected call of TX.
func (mr *MockIStoreMockRecorder) TX(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TX", reflect.TypeOf((*MockIStore)(nil).TX), ctx, fn)
}
