// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robinlg/agentops-platform/internal/store (interfaces: AgentRunStore)
//
// Generated by this command:
//
//	mockgen -destination mock_agent_run.go -package store github.com/robinlg/agentops-platform/internal/store AgentRunStore
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	model "github.com/robinlg/agentops-platform/internal/model"
	where "github.com/robinlg/onexlib/pkg/store/where"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentRunStore is a mock of AgentRunStore interface.
type MockAgentRunStore struct {
	ctrl     *gomock.Controller
	recorder *MockAgentRunStoreMockRecorder
	isgomock struct{}
}

// MockAgentRunStoreMockRecorder is the mock recorder for MockAgentRunStore.
type MockAgentRunStoreMockRecorder struct {
	mock *MockAgentRunStore
}

// NewMockAgentRunStore creates a new mock instance.
func NewMockAgentRunStore(ctrl *gomock.Controller) *MockAgentRunStore {
	mock := &MockAgentRunStore{ctrl: ctrl}
	mock.recorder = &MockAgentRunStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentRunStore) EXPECT() *MockAgentRunStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAgentRunStore) Create(ctx context.Context, obj *model.AgentRunM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAgentRunStoreMockRecorder) Create(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentRunStore)(nil).Create), ctx, obj)
}

// Delete mocks base method.
func (m *MockAgentRunStore) Delete(ctx context.Context, opts *where.Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentRunStoreMockRecorder) Delete(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentRunStore)(nil).Delete), ctx, opts)
}

// Get mocks base method.
func (m *MockAgentRunStore) Get(ctx context.Context, opts *where.Options) (*model.AgentRunM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, opts)
	ret0, _ := ret[0].(*model.AgentRunM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAgentRunStoreMockRecorder) Get(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentRunStore)(nil).Get), ctx, opts)
}

// List mocks base method.
func (m *MockAgentRunStore) List(ctx context.Context, opts *where.Options) (int64, []*model.AgentRunM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]*model.AgentRunM)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAgentRunStoreMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAgentRunStore)(nil).List), ctx, opts)
}

// Update mocks base method.
func (m *MockAgentRunStore) Update(ctx context.Context, obj *model.AgentRunM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAgentRunStoreMockRecorder) Update(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAgentRunStore)(nil).Update), ctx, obj)
}
