// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/robinlg/agentops-platform/internal/biz"
	"github.com/robinlg/agentops-platform/internal/llm"
	"github.com/robinlg/agentops-platform/internal/pkg/server"
	"github.com/robinlg/agentops-platform/internal/runtime"
	"github.com/robinlg/agentops-platform/internal/store"
)

// Injectors from wire.go:

func InitializeWebServer(config *Config) (server.Server, error) {
	string2 := config.ServerMode
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	datastore := store.NewStore(db)
	promptBuilder := runtime.NewPromptBuilder()
	client := llm.NewClient()
	bizBiz := biz.NewBiz(datastore, promptBuilder, client)
	serverConfig := &ServerConfig{
		cfg: config,
		biz: bizBiz,
	}
	serverServer, err := NewWebServer(string2, serverConfig)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
