// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentM = "agents"

// AgentM mapped from table <agents>
type AgentM struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name            string    `gorm:"column:name;not null;comment:智能体名称" json:"name"`                                      // 智能体名称
	Description     *string   `gorm:"column:description;comment:智能体描述" json:"description"`                                 // 智能体描述
	SystemPrompt    *string   `gorm:"column:system_prompt;comment:系统提示" json:"system_prompt"`                              // 系统提示
	ModelProviderID int64     `gorm:"column:model_provider_id;not null;comment:模型提供商ID" json:"model_provider_id"`          // 模型提供商ID
	Model           *string   `gorm:"column:model;comment:模型" json:"model"`                                                // 模型
	Temperature     *float64  `gorm:"column:temperature;default:0.7;comment:热度" json:"temperature"`                        // 热度
	MaxTokens       *int32    `gorm:"column:max_tokens;default:2048;comment:最大token" json:"max_tokens"`                    // 最大token
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName AgentM's table name
func (*AgentM) TableName() string {
	return TableNameAgentM
}
