// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robinlg/agentops-platform/internal/biz (interfaces: IBiz)
//
// Generated by this command:
//
//	mockgen -destination mock_biz.go -package biz github.com/robinlg/agentops-platform/internal/biz IBiz
//

// Package biz is a generated GoMock package.
package biz

import (
	reflect "reflect"

	agent "github.com/robinlg/agentops-platform/internal/biz/v1/agent"
	agentrun "github.com/robinlg/agentops-platform/internal/biz/v1/agent-run"
	chat "github.com/robinlg/agentops-platform/internal/biz/v1/chat"
	conversation "github.com/robinlg/agentops-platform/internal/biz/v1/conversation"
	model_provider "github.com/robinlg/agentops-platform/internal/biz/v1/model-provider"
	gomock "go.uber.org/mock/gomock"
)

// MockIBiz is a mock of IBiz interface.
type MockIBiz struct {
	ctrl     *gomock.Controller
	recorder *MockIBizMockRecorder
	isgomock struct{}
}

// MockIBizMockRecorder is the mock recorder for MockIBiz.
type MockIBizMockRecorder struct {
	mock *MockIBiz
}

// NewMockIBiz creates a new mock instance.
func NewMockIBiz(ctrl *gomock.Controller) *MockIBiz {
	mock := &MockIBiz{ctrl: ctrl}
	mock.recorder = &MockIBizMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBiz) EXPECT() *MockIBizMockRecorder {
	return m.recorder
}

// AgentRunV1 mocks base method.
func (m *MockIBiz) AgentRunV1() agentrun.AgentRunBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentRunV1")
	ret0, _ := ret[0].(agentrun.AgentRunBiz)
	return ret0
}

// AgentRunV1 indicates an expected call of AgentRunV1.
func (mr *MockIBizMockRecorder) AgentRunV1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentRunV1", reflect.TypeOf((*MockIBiz)(nil).AgentRunV1))
}

// AgentV1 mocks base method.
func (m *MockIBiz) AgentV1() agent.AgentBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentV1")
	ret0, _ := ret[0].(agent.AgentBiz)
	return ret0
}

// AgentV1 indicates an expected call of AgentV1.
func (mr *MockIBizMockRecorder) AgentV1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentV1", reflect.TypeOf((*MockIBiz)(nil).AgentV1))
}

// ChatV1 mocks base method.
func (m *MockIBiz) ChatV1() chat.ChatBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatV1")
	ret0, _ := ret[0].(chat.ChatBiz)
	return ret0
}

// ChatV1 indicates an expected call of ChatV1.
func (mr *MockIBizMockRecorder) ChatV1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatV1", reflect.TypeOf((*MockIBiz)(nil).ChatV1))
}

// ConversationV1 mocks base method.
func (m *MockIBiz) ConversationV1() conversation.ConversationBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConversationV1")
	ret0, _ := ret[0].(conversation.ConversationBiz)
	return ret0
}

// ConversationV1 indicates an expected call of ConversationV1.
func (mr *MockIBizMockRecorder) ConversationV1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConversationV1", reflect.TypeOf((*MockIBiz)(nil).ConversationV1))
}

// ModelProviderV1 mocks base method.
func (m *MockIBiz) ModelProviderV1() model_provider.ModelProviderBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelProviderV1")
	ret0, _ := ret[0].(model_provider.ModelProviderBiz)
	return ret0
}

// ModelProviderV1 indicates an expected call of ModelProviderV1.
func (mr *MockIBizMockRecorder) ModelProviderV1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelProviderV1", reflect.TypeOf((*MockIBiz)(nil).ModelProviderV1))
}
